apiVersion: v1
kind: Pod
metadata:
  labels:
    app: db
  name: db
spec:
  containers:
  - env:
    - name: POSTGRESQL_USER
      value: user
    - name: POSTGRESQL_PASSWORD
      value: pass
    - name: POSTGRESQL_DATABASE
      value: db
#   image: public.ecr.aws/arkcase/postgres:latest

    # Generic postgres 
    image: registry.redhat.io/rhel8/postgresql-13
    imagePullPolicy: Always
    name: db
    ports:
    - containerPort: 5432
      name: dbport
      protocol: TCP
  hostname: db
  imagePullSecrets:
  # Nathan's redhat account
  - name: redhat-io-nathanobert
